### ISSUE TITLE
"No results matching query were found."

### ISSUE THREAD

**Issue by bragilee** [nhynes/caffegraph#1]
Hi, I am trying to use your repo to load caffe model in the torch. But when I follow the instructions below, I have got the following issue:
"No results matching query were found."

I am a bit confused and I am looking forward to your help.

**Comment by nhynes** [comment]
Thanks for the bug report! I just submitted a PR to the [torch/rocks](https://github.com/torch/rocks/pull/124) repo. Once that's merged, you'll be able to do `luarocks install caffegraph` as per usual.

Until then, however, you're probably best off just cloning the repo and running

`luarocks build rocks/caffegraph-scm-1.rockspec`.

**Comment by bragilee** [comment]
Thank you for your help, I will have a try with this method. :)

---

Best Regards,
Bragi Lee
