### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by omniasaleh** [nhynes/caffegraph#11]
get Segmentation fault (core dumped) when try loadcaffe.load
prototxt file https://github.com/richzhang/colorization/blob/master/colorization/models/colorization_deploy_v2.prototxt
caffemodel
http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2.caffemodel

**Comment by nhynes** [comment]
Most probably because there's a node definition missing. Unfortunately caffe1 (and torch7) are _super_ old and quite deprecated. I think you'd probably have an easier time rewriting the model from the linked paper in pytorch directly :)
