### ISSUE TITLE
loading bn layer

### ISSUE THREAD

**Issue by jeanne-wang** [nhynes/caffegraph#2]
Hi, 
It seems that caffegraph now cannot load bn layer, right? Because when I was loading the GoogleNet+BN model that was trained by myself, there come out the following error:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 58:12: Message type "caffe.LayerParameter" has no field named "bn_param".

**Comment by nhynes** [comment]
Does e4084c6e2c318e2f02474c9ab589185efb70a9da fix your problem?
