### ISSUE TITLE
loading bvlc googlenet using caffegraph

### ISSUE THREAD

**Issue by AmmarahFarooqnust** [nhynes/caffegraph#4]
I am getting segmentation fault whenever i try method explained here for loading googlenet. can anybody help me to understand the issue. Thanx

**Comment by nhynes** [comment]
Would you mind posting a link to your prototxt and caffemodel?

Caffegraph supports the most recent GoogleNet (see #3).

**Comment by AmmarahFarooqnust** [comment]
Thank you for your response.
If you don't mind can you give me the link of that recent GoogleNet which
is already supported.

**Comment by nhynes** [comment]
Perhaps you could try [this model](https://drive.google.com/open?id=0BxSXpyoUGQZHOTVRWHRxWGRadlk) and then check if it matches what you want?

**Comment by AmmarahFarooqnust** [comment]
getting this error now :

caffegraph/init.lua:23: Unable to load model.

**Comment by nhynes** [comment]
Are you sure you have the filenames right?

**Comment by AmmarahFarooqnust** [comment]
I am sorry, I am disturbing you again and agian.

But I want to know that we load a model from caffe to torch then whether we
have to check to for BGR to RGB conversion and row major or column major
things like that or it is already done (or checked) while loading and we
can just use the model as it is.

Thanks.

**Comment by nhynes** [comment]
Hey, no worries! I'm more than happy to help :)

To answer your question, the model you load is exactly what was originally trained. For instance, if you load the VGG from the Caffe Model Zoo, you're going to get a net that expects BGR and values in [0,255]. They're all in row-major order by default.
